--Q1. what is the total revenue generated by male and female customers?
select
gender,
sum(purchase_amount) as revenue
from customer_pro
group by gender;

--Q2 . which customers used a discount but still spent more than average purchase amount?
select * from customer_pro;


select customer_id,purchase_amount
from customer_pro
where discount_applied ='Yes' 
and purchase_amount >=(select 
avg(purchase_amount)
from customer_pro);

--Q3 . which are the top 5 products with hihest average review rating?

select item_purchased,round(avg(review_rating::numeric),2) as avg_product_rating
from customer_pro
group by item_purchased
order by avg(review_rating)desc
limit 5;

--Q4 . compare the average purchase amount between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2)
from customer_pro
where shipping_type in('Standard','Express')
group by shipping_type;

--Q5. do subscribed customers spend more? compare average speed and total revenue between subscribed and non subscribed
select  subscription_status,count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_reveune
from customer_pro
group by subscription_status
order by avg_spend,total_reveune desc;

--Q6 . which 5 products have the highest percentage of purchase with discount applied

select
item_purchased,
round(100 * sum(case
when discount_applied ='Yes' then 1
else 0 end)/count(*),2) as discount_rate
from customer_pro
group by item_purchased
order by discount_rate desc
limit 5;

--Q7 segment customers into new returning, and loyal based on their total number of previous purchases and show the count of each segment
with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases=1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from customer_pro
)
select customer_segment,count(*) as no_of_customer
from customer_type
group by customer_segment;

--Q8 . What are the top 3 most purchased products within each category

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc)as item_rank
from customer_pro
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Q9 . are customer who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_pro
where previous_purchases >5
group by subscription_status;

--Q10 . what is the revenue contribution of each age group?
select
age_group,
sum(purchase_amount) as revenue
from customer_pro
group by age_group
order by revenue desc;
